### PR TITLE
Psr 4 refactor

### PR DESCRIPTION
**Pull request by gavinjackson**
Hi guys,

This is a refactor that enables psr-4 composer autoloading (which should address issue #12 which will also facilitate issue #18 ).

I've also updated the test cases.

### CODE REVIEW

**Comment by gavinjackson** [comment]
Needed to massage it a bit so tests pass in travis

**Comment by amasses** [comment]
Thanks @gavinjackson

**Comment by gavinjackson** [comment]
Thanks @amasses! Would you mind tagging the release "1.2.2"? That way we can pull from github directly via composer.

**Comment by amasses** [comment]
Done, you should see this now.

**Pull request merged**
